### ISSUE TITLE
The code is not here.

### ISSUE THREAD

**Issue by tdaugaard** [cisco/ampfsm#1]
I am looking for the source for this module as well as the `ampnetworkflow` module to enable AMP for Endpoints to work on Ubuntu 16.04 with a newer kernel rather than CentOS 7.4 (kernel 3.10.0693) which is very, very old.

**Comment by craig65535** [comment]
Hello @tdaugaard,

Both modules are now available: [cisco/ampfsm](https://github.com/cisco/ampfsm) [cisco/ampnetworkflow](https://github.com/cisco/ampnetworkflow)
